/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/test1.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Fish_Rig" position={[0.41, 0.16, 0.44]} rotation={[0, 0.28, 0]}>
          <primitive object={nodes.spine002} />
          <primitive object={nodes.spine007} />
          <skinnedMesh name="FishBones_low" geometry={nodes.FishBones_low.geometry} material={materials.M_Raccoon} skeleton={nodes.FishBones_low.skeleton} />
          <skinnedMesh name="FishHead_low" geometry={nodes.FishHead_low.geometry} material={materials.M_Raccoon} skeleton={nodes.FishHead_low.skeleton} />
          <skinnedMesh name="FishTail_low" geometry={nodes.FishTail_low.geometry} material={materials.M_Raccoon} skeleton={nodes.FishTail_low.skeleton} />
          <skinnedMesh name="FishTailEnd_low" geometry={nodes.FishTailEnd_low.geometry} material={materials.M_Raccoon} skeleton={nodes.FishTailEnd_low.skeleton} />
        </group>
        <mesh name="Ears_low" geometry={nodes.Ears_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="Tail_low" geometry={nodes.Tail_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="Head_low" geometry={nodes.Head_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="Suit_low" geometry={nodes.Suit_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="TieKnot_low" geometry={nodes.TieKnot_low.geometry} material={materials.M_Raccoon} position={[0, 1.02, 0.13]} rotation={[-0.75, 0, 0]} />
        <mesh name="TieTail_low" geometry={nodes.TieTail_low.geometry} material={materials.M_Raccoon} position={[0, 1, 0.15]} rotation={[-0.42, 0, 3.13]} />
        <mesh name="Suitcase_low" geometry={nodes.Suitcase_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseStompstoppers_low" geometry={nodes.SuitcaseStompstoppers_low.geometry} material={materials.M_Raccoon} position={[0.45, 0.08, 0.68]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseHandle_low" geometry={nodes.SuitcaseHandle_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.49, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="Shirt_low" geometry={nodes.Shirt_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="Pot_low" geometry={nodes.Pot_low.geometry} material={materials.M_Raccoon} position={[-0.11, 2.33, -0.39]} rotation={[-0.28, -0.07, 0.3]} />
        <mesh name="PileOfDirt_low" geometry={nodes.PileOfDirt_low.geometry} material={materials.M_Raccoon} position={[0, 2.01, -0.28]} rotation={[0.27, 0, 0]} />
        <mesh name="PiceOfDirt_low" geometry={nodes.PiceOfDirt_low.geometry} material={materials.M_Raccoon} position={[0.19, 1.87, 0.06]} rotation={[0.27, 0.32, 0.04]} />
        <mesh name="SuitcaseSuportFeet_low" geometry={nodes.SuitcaseSuportFeet_low.geometry} material={materials.M_Raccoon} position={[0.43, 0.02, 0.62]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseHingeBase_low" geometry={nodes.SuitcaseHingeBase_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.23, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseHingeCylinder_low" geometry={nodes.SuitcaseHingeCylinder_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.23, 0.45]} rotation={[Math.PI / 2, 0, -0.28]} />
        <mesh name="SuitcaseHandleBase_low" geometry={nodes.SuitcaseHandleBase_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[Math.PI / 2, 0, -0.28]} />
        <mesh name="SuitcaseLockHinge_low" geometry={nodes.SuitcaseLockHinge_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[Math.PI, -0.28, Math.PI]} />
        <mesh name="SuitcaseLockBase_low" geometry={nodes.SuitcaseLockBase_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseLockCube_low" geometry={nodes.SuitcaseLockCube_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitcaseLockHingeBase_low" geometry={nodes.SuitcaseLockHingeBase_low.geometry} material={materials.M_Raccoon} position={[0.36, 0.22, 0.47]} rotation={[0, 0.28, 0]} />
        <mesh name="SuitButton_low" geometry={nodes.SuitButton_low.geometry} material={materials.M_Raccoon} position={[0.04, 0.84, 0.25]} rotation={[-1.95, -0.15, -2.78]} />
        <mesh name="ButtonStich1_low" geometry={nodes.ButtonStich1_low.geometry} material={materials.M_Raccoon} position={[0.05, 0.85, 0.26]} rotation={[0.88, -0.58, -0.43]} />
        <mesh name="ButtonStich2_low" geometry={nodes.ButtonStich2_low.geometry} material={materials.M_Raccoon} position={[0.05, 0.85, 0.26]} rotation={[-1.56, -0.87, -2.57]} />
        <mesh name="Nails_low" geometry={nodes.Nails_low.geometry} material={materials.M_Raccoon} position={[0.42, 0.22, 0.45]} rotation={[0, 0.28, 0]} />
        <mesh name="Body_low" geometry={nodes.Body_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
        <mesh name="Spork_low" geometry={nodes.Spork_low.geometry} material={materials.M_Raccoon} position={[-0.01, 0, 0.08]} rotation={[-1.49, 0.2, 3.04]} />
        <mesh name="Footprint_1" geometry={nodes.Footprint_1.geometry} material={materials.M_Environment} position={[0, 0, -0.44]} rotation={[-Math.PI, 0.08, -Math.PI]} />
        <mesh name="Footprint_2" geometry={nodes.Footprint_2.geometry} material={materials.M_Environment} position={[0.21, 0, -0.52]} rotation={[-Math.PI, 0.08, -Math.PI]} />
        <mesh name="Footprint_3" geometry={nodes.Footprint_3.geometry} material={materials.M_Environment} position={[0.07, 0, -0.76]} rotation={[-Math.PI, 0.08, -Math.PI]} />
        <mesh name="Ground" geometry={nodes.Ground.geometry} material={materials.M_Environment} />
        <mesh name="Continue_Arrow" geometry={nodes.Continue_Arrow.geometry} material={materials.M_EnvironmentLit} position={[0, -0.24, 1.63]} scale={[0.04, 0.02, 0.03]} />
      </group>
    </group>
  )
}

useGLTF.preload('/test1.gltf')
