/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: porgy (https://sketchfab.com/porgy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pusheen-29c584aded38446f846b351be7d11c97
Title: Pusheen
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.46}>
          <group name="03d3141f73a1415c8fb3284a81209be1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plane032" position={[-256.14, 45.38, 137.34]} rotation={[0, 0.13, -3.11]} scale={[10.63, 4.62, 77.45]}>
                  <mesh name="Plane032_Material023_0" geometry={nodes.Plane032_Material023_0.geometry} material={materials['Material.023']} />
                </group>
                <group name="Cylinder006" position={[-39.48, 33.25, 156.22]} rotation={[-1.99, 0, 0.1]} scale={[114.21, 145.39, 33.32]}>
                  <mesh name="Cylinder006_Material028_0" geometry={nodes.Cylinder006_Material028_0.geometry} material={materials['Material.028']} />
                </group>
                <group name="Armature" position={[105.68, 22.89, -78.48]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={32.61}>
                  <group name="Object_9">
                    <group name="HandR_011_scaleCompensation" position={[-5.56, -6.83, -4.49]} scale={0.03}>
                      <primitive object={nodes.HandR_011} />
                    </group>
                    <group name="Bone-Mouth_012_scaleCompensation" position={[-7.93, -5.84, -3.31]} scale={0.03}>
                      <primitive object={nodes['Bone-Mouth_012']} />
                    </group>
                    <group name="body_013_scaleCompensation" position={[-3.03, -2.64, -3.53]} scale={0.03}>
                      <primitive object={nodes.body_013} />
                    </group>
                    <group name="LegL_014_scaleCompensation" position={[-0.26, -7.24, -2.22]} scale={0.03}>
                      <primitive object={nodes.LegL_014} />
                    </group>
                    <group name="lollipop_015_scaleCompensation" position={[-7.49, -6.27, -2.86]} scale={0.03}>
                      <primitive object={nodes.lollipop_015} />
                    </group>
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_11" position={[166.05, 22.46, 3.39]} scale={19.78} />
                    <group name="Cylinder001" position={[0.01, -2.51, 1.85]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.61} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.028']} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Material.027']} skeleton={nodes.Object_13.skeleton} />
                  </group>
                </group>
                <group name="Cylinder004" position={[31.27, 213.86, 136.46]} rotation={[2.42, -0.05, -0.13]} scale={[114.2, 145.39, 33.32]}>
                  <mesh name="Cylinder004_Material028_0" geometry={nodes.Cylinder004_Material028_0.geometry} material={materials['Material.028']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
