SELECT REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, REST_INFO.FAVORITES, REST_INFO.ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW LEFT JOIN REST_INFO
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_INFO.REST_ID
HAVING REST_INFO.ADDRESS LIKE '서울%'
ORDER BY AVG(REST_REVIEW.REVIEW_SCORE) DESC, REST_INFO.FAVORITES DESC



서울로 ‘시작‘하는 주소 (LIKE “서울%”)
리뷰가 없으면 조회하면 안된다.(REST_REVIEW 테이블을 기준으로 LEFT JOIN)
정렬 조건 잘 보기

